### ISSUE TITLE
 Unknown receiver 'FlutterNumberCaptcha'; did you mean 'FlutterNumberCaptchaPlugin'?

### ISSUE THREAD

**Issue by tranphuc269** [lustea00/flutter_number_captcha#2]
Hi Lustea00, I have Semantic Issue in IOS for flutter_number_captcha,
![Screen Shot 2022-07-18 at 17 00 28](https://user-images.githubusercontent.com/90142169/179488797-e2afc0f5-d9e0-49ae-bd8b-9fee034e00e6.png)
I looking forward to receiving your reply.

**Comment by ahmdhsm** [comment]
hi @tranphuc269, thank you for your report
fix already uploaded in new version
